#!/bin/sh
# Qadam Flow — one-line installer & launcher.
#
# Paste this into any macOS / Linux / WSL2 shell:
#   curl -fsSL https://flow.aiqadam.org/run.sh | sh
#
# What it does (no git, no source build):
#   1. Verifies docker + docker compose are available.
#   2. Downloads docker-compose.yml into ./qadam-flow.
#   3. Generates a fresh .env with random secrets.
#   4. docker compose pull → docker compose up -d.
#   5. Waits for the API to start and prints the URL.
#
# Environment overrides:
#   QADAM_FLOW_DIR   — install directory (default: ./qadam-flow)
#   QADAM_FLOW_PORT  — host port for the app (default: 8080)
#   QADAM_FLOW_IMAGE — docker image (default: ghcr.io/aiqadam/qadam-flow:latest)
#   QADAM_FLOW_REF   — git ref for the compose file (default: main)
#
# Targets: macOS (Docker Desktop), Linux (dockerd), Windows via WSL2.
# Native Windows PowerShell is not supported — use WSL2.

set -eu

# ---------- colors -----------------------------------------------------------

if [ -t 1 ] && [ -z "${NO_COLOR:-}" ]; then
  C_TEAL=$(printf '\033[38;5;37m')
  C_BOLD=$(printf '\033[1m')
  C_DIM=$(printf '\033[2m')
  C_RED=$(printf '\033[31m')
  C_YELLOW=$(printf '\033[33m')
  C_RESET=$(printf '\033[0m')
else
  C_TEAL=''; C_BOLD=''; C_DIM=''; C_RED=''; C_YELLOW=''; C_RESET=''
fi

log()  { printf '%s▸%s %s\n' "$C_TEAL"   "$C_RESET" "$1"; }
warn() { printf '%s!%s %s\n' "$C_YELLOW" "$C_RESET" "$1" >&2; }
err()  { printf '%s✗%s %s\n' "$C_RED"    "$C_RESET" "$1" >&2; }
die()  { err "$1"; exit 1; }

# ---------- defaults ---------------------------------------------------------

QADAM_FLOW_DIR=${QADAM_FLOW_DIR:-qadam-flow}
QADAM_FLOW_PORT=${QADAM_FLOW_PORT:-8080}
QADAM_FLOW_IMAGE=${QADAM_FLOW_IMAGE:-ghcr.io/aiqadam/qadam-flow:latest}
QADAM_FLOW_REF=${QADAM_FLOW_REF:-main}

COMPOSE_URL="https://raw.githubusercontent.com/aiqadam/qadam-flow/${QADAM_FLOW_REF}/docker-compose.yml"
HEALTH_URL="http://localhost:${QADAM_FLOW_PORT}/api/v1/flags"

# ---------- platform sanity --------------------------------------------------

detect_platform() {
  uname_s=$(uname -s 2>/dev/null || echo unknown)
  case "$uname_s" in
    Darwin)  PLATFORM=macos ;;
    Linux)
      if grep -qiE 'microsoft|wsl' /proc/version 2>/dev/null; then
        PLATFORM=wsl
      else
        PLATFORM=linux
      fi
      ;;
    MINGW*|MSYS*|CYGWIN*)
      die "native Windows shell detected — please re-run from WSL2 (https://learn.microsoft.com/windows/wsl/install)"
      ;;
    *) PLATFORM=$uname_s ;;
  esac
}

# ---------- prereqs ----------------------------------------------------------

need() {
  command -v "$1" >/dev/null 2>&1 || die "missing dependency: $1 — install it and re-run"
}

compose() {
  if docker compose version >/dev/null 2>&1; then
    docker compose "$@"
  else
    docker-compose "$@"
  fi
}

check_docker_compose() {
  if docker compose version >/dev/null 2>&1; then return 0; fi
  if command -v docker-compose >/dev/null 2>&1; then return 0; fi
  die "docker compose not found — install Docker Desktop or the docker-compose-plugin package"
}

check_docker_daemon() {
  if ! docker info >/dev/null 2>&1; then
    case "$PLATFORM" in
      macos) die "Docker Desktop isn't running — open it and wait until the whale icon goes steady" ;;
      wsl)   die "docker daemon unreachable — start Docker Desktop on Windows with WSL integration enabled" ;;
      *)     die "docker daemon unreachable — run: sudo systemctl start docker" ;;
    esac
  fi
}

check_prereqs() {
  need curl
  need openssl
  need docker
  check_docker_compose
  check_docker_daemon
}

# ---------- staging directory ------------------------------------------------

prepare_dir() {
  if [ -d "$QADAM_FLOW_DIR" ]; then
    if [ -f "$QADAM_FLOW_DIR/docker-compose.yml" ] && [ -f "$QADAM_FLOW_DIR/.env" ]; then
      log "found existing install at $QADAM_FLOW_DIR — refreshing compose file"
    else
      warn "$QADAM_FLOW_DIR exists but doesn't look like a Qadam Flow install — continuing anyway"
    fi
  else
    mkdir -p "$QADAM_FLOW_DIR"
  fi
  cd "$QADAM_FLOW_DIR"
}

fetch_compose() {
  log "downloading docker-compose.yml from $COMPOSE_URL"
  if ! curl -fsSL "$COMPOSE_URL" -o docker-compose.yml.new; then
    die "failed to download $COMPOSE_URL — check your network and that the repo is public"
  fi
  mv docker-compose.yml.new docker-compose.yml
}

generate_env() {
  if [ -f .env ]; then
    log "reusing existing .env (delete it to regenerate secrets)"
    return 0
  fi
  log "generating .env with fresh random secrets"
  enc_key=$(openssl rand -hex 16)
  jwt_secret=$(openssl rand -hex 32)
  pg_password=$(openssl rand -hex 12)

  cat > .env <<EOF
# Qadam Flow — generated by install.sh. Delete this file and re-run to rotate secrets.
QADAM_FLOW_IMAGE=${QADAM_FLOW_IMAGE}

AP_ENVIRONMENT=PRODUCTION
AP_FRONTEND_URL=http://localhost:${QADAM_FLOW_PORT}
AP_WEBHOOK_TIMEOUT_SECONDS=30
AP_TRIGGER_DEFAULT_POLL_INTERVAL=5

# Database
AP_DB_TYPE=POSTGRES
AP_POSTGRES_HOST=postgres
AP_POSTGRES_PORT=5432
AP_POSTGRES_DATABASE=qadam_flow
AP_POSTGRES_USERNAME=postgres
AP_POSTGRES_PASSWORD=${pg_password}
AP_POSTGRES_USE_SSL=false

# Queue + cache
AP_QUEUE_MODE=REDIS
AP_REDIS_HOST=redis
AP_REDIS_PORT=6379

# Secrets — regenerated per install
AP_ENCRYPTION_KEY=${enc_key}
AP_JWT_SECRET=${jwt_secret}

# Telemetry + community
AP_TELEMETRY_ENABLED=false
AP_QADAMS_SYNC_MODE=NONE
AP_TEMPLATES_SOURCE_URL=

# Engine
AP_EXECUTION_MODE=UNSANDBOXED
AP_FLOW_WORKER_CONCURRENCY=10
EOF
}

# ---------- run --------------------------------------------------------------

pull_and_up() {
  log "pulling ${QADAM_FLOW_IMAGE} (≈400 MB, one-time)"
  compose pull
  log "starting postgres, redis, app, and workers"
  compose up -d
}

wait_for_app() {
  log "waiting for the app at ${HEALTH_URL}"
  deadline=$(( $(date +%s) + 180 ))
  while [ "$(date +%s)" -lt "$deadline" ]; do
    if curl -fsS -m 2 "$HEALTH_URL" >/dev/null 2>&1; then
      log "app is up"
      return 0
    fi
    sleep 2
  done
  err "app didn't respond within 3 min — check: cd $QADAM_FLOW_DIR && docker compose logs app"
  return 1
}

# ---------- banner -----------------------------------------------------------

banner() {
  cat <<EOF
${C_TEAL}${C_BOLD}
   Qadam Flow installer
${C_RESET}${C_DIM}an AI Qadam Build project — https://flow.aiqadam.org${C_RESET}

EOF
}

final_banner() {
  cat <<EOF

${C_TEAL}${C_BOLD}Qadam Flow${C_RESET} is running at ${C_BOLD}http://localhost:${QADAM_FLOW_PORT}${C_RESET}
   installed in ${C_BOLD}$(pwd)${C_RESET}

${C_DIM}First-time onboarding:${C_RESET}
  1. Open ${C_BOLD}http://localhost:${QADAM_FLOW_PORT}/sign-up${C_RESET} — first signup owns the platform.
  2. Name the platform when prompted.
  3. From the welcome dashboard, pick a template or start a flow from scratch.

${C_DIM}Common commands (from $(pwd)):${C_RESET}
  docker compose logs -f app worker   follow logs
  docker compose down                 stop (keep data)
  docker compose down -v              stop AND wipe data
  docker compose pull && docker compose up -d   update to latest image

${C_DIM}an AI Qadam Build project — https://flow.aiqadam.org${C_RESET}
EOF
}

# ---------- main -------------------------------------------------------------

main() {
  banner
  detect_platform
  log "platform: $PLATFORM"
  check_prereqs
  prepare_dir
  fetch_compose
  generate_env
  pull_and_up
  wait_for_app
  final_banner
}

main "$@"
