// @vitest-environment jsdom
import { FormInputType, FormResponse } from '@aiqadam/shared';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import * as React from 'react';
import { act } from 'react';
import { createRoot, Root } from 'react-dom/client';
import { MemoryRouter } from 'react-router-dom';
import { afterEach, beforeAll, describe, expect, it, vi } from 'vitest';

import { humanInputApi } from '@/features/forms/api/human-input-api';
import { ApForm } from '@/features/forms/components/ap-form';

vi.mock('@/hooks/flags-hooks', () => ({
  flagsHooks: {
    useFlag: () => ({ data: false }),
  },
}));

vi.mock('@/features/forms/api/human-input-api', () => ({
  humanInputApi: {
    submitForm: vi.fn(),
  },
}));

const toastSpies = vi.hoisted(() => ({
  error: vi.fn(),
  info: vi.fn(),
  success: vi.fn(),
}));

vi.mock('sonner', () => ({
  toast: toastSpies,
}));

// i18next is not initialised in this harness, so the real `t` answers ''.
vi.mock('i18next', async (importOriginal) => ({
  ...(await importOriginal<typeof import('i18next')>()),
  t: (key: string) => key,
}));

let container: HTMLDivElement | undefined;
let root: Root | undefined;

const flush = async (): Promise<void> => {
  await act(async () => {
    await new Promise((r) => setTimeout(r, 0));
  });
};

const toggleForm: FormResponse = {
  id: 'form-1',
  title: 'A form with a toggle',
  projectId: 'project-1',
  version: '1',
  props: {
    waitForResponse: false,
    inputs: [
      {
        displayName: 'Enable notifications',
        required: false,
        description: '',
        type: FormInputType.TOGGLE,
      },
    ],
  },
};

const mount = async (): Promise<void> => {
  const queryClient = new QueryClient({
    defaultOptions: { queries: { retry: false } },
  });
  container = document.createElement('div');
  document.body.appendChild(container);
  root = createRoot(container);
  await act(async () => {
    root?.render(
      <MemoryRouter>
        <QueryClientProvider client={queryClient}>
          <ApForm form={toggleForm} useDraft={false} />
        </QueryClientProvider>
      </MemoryRouter>,
    );
  });
  await flush();
};

beforeAll(() => {
  Object.assign(globalThis, { IS_REACT_ACT_ENVIRONMENT: true });
  // radix-ui's Checkbox measures itself via ResizeObserver, which jsdom does not implement.
  class NoopResizeObserver {
    observe() {}
    unobserve() {}
    disconnect() {}
  }
  Object.assign(globalThis, { ResizeObserver: NoopResizeObserver });
});

afterEach(async () => {
  await act(async () => {
    root?.unmount();
  });
  container?.remove();
  container = undefined;
  root = undefined;
  vi.clearAllMocks();
});

describe('ApForm toggle input label', () => {
  // #345 (case 1): the label passed an explicit `htmlFor={input.name}`, which — because
  // `FormLabel` spreads its own props after setting its default `htmlFor={formItemId}` —
  // silently overrode the id `FormControl` actually assigns to the `Checkbox`. A grep for a
  // literal `id="…"` matching `input.name` finds nothing to fix because nothing was ever meant
  // to carry that literal id; the real id is generated by `useId()` inside `FormItem`.
  it('resolves the toggle label to the checkbox it is next to, via getElementById(htmlFor)', async () => {
    await mount();

    const label = [...(container?.querySelectorAll('label') ?? [])].find((el) =>
      el.textContent?.includes('Enable notifications'),
    );
    expect(label).toBeDefined();

    const forId = label?.getAttribute('for');
    expect(forId).toBeTruthy();

    const control = forId ? document.getElementById(forId) : null;
    expect(control).not.toBeNull();
    expect(control?.getAttribute('role')).toBe('checkbox');
  });

  it('toggles the checkbox when its label is clicked', async () => {
    await mount();

    const label = [...(container?.querySelectorAll('label') ?? [])].find((el) =>
      el.textContent?.includes('Enable notifications'),
    );
    const forId = label?.getAttribute('for');
    const control = forId
      ? (document.getElementById(forId) as HTMLElement | null)
      : null;

    expect(control?.getAttribute('data-state')).toBe('unchecked');

    await act(async () => {
      label?.dispatchEvent(new MouseEvent('click', { bubbles: true }));
    });
    await flush();

    expect(control?.getAttribute('data-state')).toBe('checked');
  });
});

describe('ApForm submission errors', () => {
  const submitAndFlush = async (): Promise<void> => {
    const submitButton = [
      ...(container?.querySelectorAll('button[type="submit"]') ?? []),
    ].find(
      (element): element is HTMLButtonElement =>
        element instanceof HTMLButtonElement,
    );
    await act(async () => {
      submitButton?.dispatchEvent(
        new MouseEvent('click', { bubbles: true, cancelable: true }),
      );
    });
    await flush();
  };

  // 503 means the sync webhook refused the submission outright (unlike the 504 case, where
  // it was accepted and is merely still running), so it must not share the 504 branch's
  // toast.info styling — see error-bubble's CHAT_SERVICE_UNAVAILABLE for the chat-side twin.
  it('shows a distinct, retryable toast.error on a 503, not the 504 toast.info', async () => {
    vi.mocked(humanInputApi.submitForm).mockRejectedValueOnce(
      Object.assign(new Error('Service Unavailable'), {
        isAxiosError: true,
        response: {
          status: 503,
          data: { message: 'Too many concurrent runs.' },
        },
      }),
    );

    await mount();
    await submitAndFlush();

    expect(toastSpies.error).toHaveBeenCalledWith(
      'The service is temporarily busy. Please try again in a moment.',
      expect.objectContaining({ duration: 3000 }),
    );
    expect(toastSpies.info).not.toHaveBeenCalled();
  });

  it('shows the honest "may still be running" toast.info on a 504', async () => {
    vi.mocked(humanInputApi.submitForm).mockRejectedValueOnce(
      Object.assign(new Error('Gateway Timeout'), {
        isAxiosError: true,
        response: { status: 504, data: { message: 'Still running.' } },
      }),
    );

    await mount();
    await submitAndFlush();

    // #510: a run that hadn't started by the deadline is now failed, not "still
    // running" — the toast must not claim the submission is safely in progress, must
    // not point at the run history (an anonymous submitter can't open it), and needs
    // longer than the default 3000ms to be read.
    expect(toastSpies.info).toHaveBeenCalledWith(
      "The flow did not finish in time and may still be running. Please don't resubmit right away.",
      expect.objectContaining({ duration: 8000 }),
    );
    expect(toastSpies.error).not.toHaveBeenCalled();
  });
});
