// @vitest-environment jsdom
import { FormInputType, FormResponse } from '@aiqadam/shared';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import * as React from 'react';
import { act } from 'react';
import { createRoot, Root } from 'react-dom/client';
import { MemoryRouter } from 'react-router-dom';
import { afterEach, beforeAll, describe, expect, it, vi } from 'vitest';

import { ApForm } from '@/features/forms/components/ap-form';

vi.mock('@/hooks/flags-hooks', () => ({
  flagsHooks: {
    useFlag: () => ({ data: false }),
  },
}));

vi.mock('@/features/forms/api/human-input-api', () => ({
  humanInputApi: {
    submitForm: vi.fn(),
  },
}));

let container: HTMLDivElement | undefined;
let root: Root | undefined;

const flush = async (): Promise<void> => {
  await act(async () => {
    await new Promise((r) => setTimeout(r, 0));
  });
};

const toggleForm: FormResponse = {
  id: 'form-1',
  title: 'A form with a toggle',
  projectId: 'project-1',
  version: '1',
  props: {
    waitForResponse: false,
    inputs: [
      {
        displayName: 'Enable notifications',
        required: false,
        description: '',
        type: FormInputType.TOGGLE,
      },
    ],
  },
};

const mount = async (): Promise<void> => {
  const queryClient = new QueryClient({
    defaultOptions: { queries: { retry: false } },
  });
  container = document.createElement('div');
  document.body.appendChild(container);
  root = createRoot(container);
  await act(async () => {
    root?.render(
      <MemoryRouter>
        <QueryClientProvider client={queryClient}>
          <ApForm form={toggleForm} useDraft={false} />
        </QueryClientProvider>
      </MemoryRouter>,
    );
  });
  await flush();
};

beforeAll(() => {
  Object.assign(globalThis, { IS_REACT_ACT_ENVIRONMENT: true });
  // radix-ui's Checkbox measures itself via ResizeObserver, which jsdom does not implement.
  class NoopResizeObserver {
    observe() {}
    unobserve() {}
    disconnect() {}
  }
  Object.assign(globalThis, { ResizeObserver: NoopResizeObserver });
});

afterEach(async () => {
  await act(async () => {
    root?.unmount();
  });
  container?.remove();
  container = undefined;
  root = undefined;
});

describe('ApForm toggle input label', () => {
  // #345 (case 1): the label passed an explicit `htmlFor={input.name}`, which — because
  // `FormLabel` spreads its own props after setting its default `htmlFor={formItemId}` —
  // silently overrode the id `FormControl` actually assigns to the `Checkbox`. A grep for a
  // literal `id="…"` matching `input.name` finds nothing to fix because nothing was ever meant
  // to carry that literal id; the real id is generated by `useId()` inside `FormItem`.
  it('resolves the toggle label to the checkbox it is next to, via getElementById(htmlFor)', async () => {
    await mount();

    const label = [...(container?.querySelectorAll('label') ?? [])].find(
      (el) => el.textContent?.includes('Enable notifications'),
    );
    expect(label).toBeDefined();

    const forId = label?.getAttribute('for');
    expect(forId).toBeTruthy();

    const control = forId ? document.getElementById(forId) : null;
    expect(control).not.toBeNull();
    expect(control?.getAttribute('role')).toBe('checkbox');
  });

  it('toggles the checkbox when its label is clicked', async () => {
    await mount();

    const label = [...(container?.querySelectorAll('label') ?? [])].find(
      (el) => el.textContent?.includes('Enable notifications'),
    );
    const forId = label?.getAttribute('for');
    const control = forId
      ? (document.getElementById(forId) as HTMLElement | null)
      : null;

    expect(control?.getAttribute('data-state')).toBe('unchecked');

    await act(async () => {
      label?.dispatchEvent(new MouseEvent('click', { bubbles: true }));
    });
    await flush();

    expect(control?.getAttribute('data-state')).toBe('checked');
  });
});
